### ISSUE TITLE
[BUG] test_salvage_auto_crash_replicas_short_wait and  test_salvage_auto_crash_all_replicas fails sometimes due to fast pod restart

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1742]
**Describe the bug**
tests `test_salvage_auto_crash_replicas_short_wait` and `test_salvage_auto_crash_all_replicas` fails if pod restarted too quickly before `wait_for_pod_restart` and `wait_for_pod_remount` executes

**To Reproduce**
1. Install Longhorn using master images
2. run tests

**Expected behavior**
tests should pass

**Log**
```
>       wait_pod_for_auto_salvage(client, core_api, volume_name, pod_name, md5sum)

client     = <longhorn.Client object at 0x7f8959260c10>
core_api   = <kubernetes.client.apis.core_v1_api.CoreV1Api object at 0x7f89592a2d50>
csi_pv     = {'apiVersion': 'v1',
 'kind': 'PersistentVolume',
 'metadata': {'name': 'longhorn-testvol-36y3aw-pv'},
 'spec': {'accessModes': ['ReadWriteOnce'],
          'capacity': {'storage': '1073741824'},
          'csi': {'driver': 'driver.longhorn.io',
                  'fsType': 'ext4',
                  'volumeAttributes': {'numberOfReplicas': '3',
                                       'staleReplicaTimeout': '30'},
                  'volumeHandle': 'longhorn-testvol-36y3aw'},
          'persistentVolumeReclaimPolicy': 'Delete',
          'volumeMode': 'Filesystem'}}
md5sum     = 'e41c30d864de54e186a2fb1c25f50c62\n'
pod_make   = <function pod_make.<locals>.make_pod at 0x7f89592ef200>
pod_name   = 'longhorn-testvol-36y3aw-pod'
pv_name    = 'longhorn-testvol-36y3aw-pv'
pvc        = {'apiVersion': 'v1',
 'kind': 'PersistentVolumeClaim',
 'metadata': {'name': 'longhorn-testvol-36y3aw-pvc'},
 'spec': {'accessModes': ['ReadWriteOnce'],
          'resources': {'requests': {'storage': '1073741824'}},
          'storageClassName': '',
          'volumeName': 'longhorn-testvol-36y3aw-pv'}}
pvc_name   = 'longhorn-testvol-36y3aw-pvc'
volume_name = 'longhorn-testvol-36y3aw'

test_ha.py:474: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_ha.py:444: in wait_pod_for_auto_salvage
    wait_for_pod_restart(core_api, pod_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

core_api = <kubernetes.client.apis.core_v1_api.CoreV1Api object at 0x7f89592a2d50>, pod_name = 'longhorn-testvol-36y3aw-pod', namespace = 'default'

    def wait_for_pod_restart(core_api, pod_name, namespace="default"):
        pod = core_api.read_namespaced_pod(name=pod_name,
                                           namespace=namespace)
        restart_count = pod.status.container_statuses[0].restart_count
    
        pod_restarted = False
        for i in range(RETRY_COUNTS):
            pod = core_api.read_namespaced_pod(name=pod_name,
                                               namespace=namespace)
            count = pod.status.container_statuses[0].restart_count
            if count > restart_count:
                pod_restarted = True
                break
    
            time.sleep(RETRY_INTERVAL)
>       assert pod_restarted
E       AssertionError


pod_restarted = False
restart_count = 1
```

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.18
 - Node OS type and version: Ubuntu 18.04

**Additional context**
[test_salvage_auto_crash_replicas_short_wait](https://ci.longhorn.io/job/public/job/longhorn-tests/70/testReport/junit/tests/test_ha/test_salvage_auto_crash_replicas_short_wait/)
[test_salvage_auto_crash_all_replicas](https://ci.longhorn.io/job/public/job/longhorn-tests/70/testReport/junit/tests/test_ha/test_salvage_auto_crash_all_replicas/)

**Comment by c3y1huang** [comment]
Fixed in https://github.com/longhorn/longhorn-tests/pull/456.

**Comment by yasker** [comment]
`tests.test_ha.test_salvage_auto_crash_all_replicas` still fails sometimes https://ci.longhorn.io/job/public/job/longhorn-tests/151/testReport/junit/tests/test_ha/test_salvage_auto_crash_all_replicas/ . (Yes, it's a tricky one)

**Comment by khushboo-rancher** [comment]
The tests `test_salvage_auto_crash_replicas_short_wait` and `test_salvage_auto_crash_all_replicas` are passing in nightly test run from more than last 10 runs.
