### ISSUE TITLE
Trying to access Longhorn UI through a Sub Path ends up in a blank white page

### ISSUE THREAD

**Issue by ianvari** [longhorn/longhorn#1745]
I'm trying to access the longhorn UI and ingress controller, nginx in my case on a K3S environment. First off I had to change the ingress YAML file found on the docs a bit to be able to get it to work, but I was able to finally access it with no issues. 

In the next step I tried customizing a bit more and accessing the UI through a subpath instead of directly on the root path and tried multiple different paths and prefix types, they all end in a blank white page, I still get a browser authentication pop up but after that it's all blank ! 

This YAML file is the one that works and I can access the dashboard through 10.0.0.220 in my case : 

```
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      # type of authentication
      nginx.ingress.kubernetes.io/auth-type: basic
      # prevent the controller from redirecting (308) to HTTPS
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      # name of the secret that contains the user/password definitions
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      # message to display with an appropriate context why the authentication is required
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    name: longhorn-ingress
    namespace: longhorn-system
  spec:
    rules:
        - http:
           paths:
            - backend:
                serviceName: longhorn-frontend
                servicePort: 80
              path: /
```

But when I add any subpath and browser to 10.0.0.220/lg or 10.0.0.220/lg/ for example I get a blank page 

```
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      # type of authentication
      nginx.ingress.kubernetes.io/auth-type: basic
      # prevent the controller from redirecting (308) to HTTPS
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      # name of the secret that contains the user/password definitions
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      # message to display with an appropriate context why the authentication is required
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    name: longhorn-ingress
    namespace: longhorn-system
  spec:
    rules:
        - http:
           paths:
            - backend:
                serviceName: longhorn-frontend
                servicePort: 80
              path: /lg/
```
Any help is much appreciated !

**Comment by smallteeths** [comment]
For the time being, this version only supports `path: /`. The next version will be updated to support any path. @ianvari @andyjeffries  @yasker 
If it is a test environment, you can try image `wangsiye/longhorn-ui:904c756`. Ingress needs to be configured correctly, annotations need to add parameters nginx.ingress.kubernetes.io/rewrite-target: /$2
path is set to /xxx(/|$)(.*)

**Comment by ianvari** [comment]
Thanks for clarifying @smallteeths, would you mind sharing your ingress YAML file after you test it so I understand where you add those parameters? 

As a work around on the stable version, is it possible to deploy a second ingress controller and dedicate the existing one to the longhorn UI? I'm a K8S newbie so still trying to learn all the bits and pieces.

**Comment by smallteeths** [comment]
`  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      # type of authentication
      nginx.ingress.kubernetes.io/auth-type: basic
      # prevent the controller from redirecting (308) to HTTPS
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      # name of the secret that contains the user/password definitions
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      # message to display with an appropriate context why the authentication is required
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    name: longhorn-ingress
    namespace: longhorn-system
  spec:
    rules:
        - http:
           paths:
            - backend:
                serviceName: longhorn-frontend
                servicePort: 80
              path: /lg(/|$)(.*)`

In this ingress definition, any characters captured by (.*) will be assigned to the placeholder $2, which is then used as a parameter in the rewrite-target annotation.

For example, the ingress definition above will result in the following rewrites:

rewrite.bar.com/something rewrites to rewrite.bar.com/
rewrite.bar.com/something/ rewrites to rewrite.bar.com/
rewrite.bar.com/something/new rewrites to rewrite.bar.com/new

It should be possible to deploy two ingresses. I haven’t tried this, but I don’t think it is necessary.

**Comment by ianvari** [comment]
Thanks a lot @smallteeths  I'll give this a try, just to clarify would this work with the current stable version or do I need to replace the UI? If so can you point me to where the image path needs to be updated?

**Comment by smallteeths** [comment]
Sorry for not getting back to you sooner @ianvari 
Use `kubectl edit -n longhorn-system deployment longhorn-ui`.
![Jietu20200902-135606](https://user-images.githubusercontent.com/27733391/91937235-13804380-ed24-11ea-8b70-119e2e81617e.jpg)

**Comment by smallteeths** [comment]
Yes it has been fixed in longhorn-ui and users can navigate to longhorn-ui using any path under the ingress proxy. Of course it must be ensured that ingress is configured correctly. @jack-newbury

**Comment by TayyabSuhail123** [comment]
Hi still facing this issue on the newest version of longhorn

**Comment by TayyabSuhail123** [comment]
> Yes it has been fixed in longhorn-ui and users can navigate to longhorn-ui using any path under the ingress proxy. Of course it must be ensured that ingress is configured correctly. @jack-newbury

Hi, I am trying to use the subpath /longhorn with the latest version but I am still getting a blank screen? Any recommendations?

**Comment by smallteeths** [comment]
You'd better provide the ingress configuration file, I think the problem should be in the ingress configuration. @TayyabSuhail123

**Comment by TayyabSuhail123** [comment]
@smallteeths 
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /longhorn
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80`

**Comment by smallteeths** [comment]
```
annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
...
spec:
    rules:
        - http:
           paths:
           - path: /longhorn(/|$)(.*)
             pathType: Prefix
```
Please edit the ingress.yaml and try again.
@TayyabSuhail123

**Comment by TayyabSuhail123** [comment]
@smallteeths 
Works perfectly mate. Cheers

**Comment by divick** [comment]
@smallteeths Though this issue is closed but thought to check if my issue can be resolved with this itself instead of creating the same ticket again. I am facing exactly the same issue that @TayyabSuhail123 is facing. I have the annotation exactly as your described and the same path but still the javascript and other assets are being looked up with path "/".

Moreover since my longhorn is deployed on a subpath "/longhorn", and if the javascripts and other assets are being looked up on path "/" it will never even reach the longhorn-ui because the nginx-controller will not even match the path "/longhorn" and hence will not even send request to longhorn-ui service. Please correct me if I have misunderstood something.

**Comment by smallteeths** [comment]
> @smallteeths Though this issue is closed but thought to check if my issue can be resolved with this itself instead of creating the same ticket again. I am facing exactly the same issue that @TayyabSuhail123 is facing. I have the annotation exactly as your described and the same path but still the javascript and other assets are being looked up with path "/".
> 
> Moreover since my longhorn is deployed on a subpath "/longhorn", and if the javascripts and other assets are being looked up on path "/" it will never even reach the longhorn-ui because the nginx-controller will not even match the path "/longhorn" and hence will not even send request to longhorn-ui service. Please correct me if I have misunderstood something.

Please add the following configuration

```
nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/css/(.*)$ /longhorn/css/$1 redirect;
      rewrite ^/js/(.*)$ /longhorn/js/$1 redirect;
```

**Comment by divick** [comment]
@smallteeths thanks for your reply but for some reason I redeployed and it worked even without you suggestions above but with original rewrite using annotation. May be I mistyped :(

I presume your changes above are equivalent to adding annotations on ingress for nginx?

**Comment by smallteeths** [comment]
I'm guessing from the information provided above that there is a problem with the path to the css/ js. So I added a css/js redirect for ingress.yaml. I'm not quite sure why the css/js requests are addressed to the root path `/xx.css | /xxx.js`. The css/js for longhorn-ui is a relative path, so the default request address should be `/longhorn/xx.css`| `/longhorn/xx.js`.

Can you provide a screenshot of the ingress configuration and js/css url requests ? @divick thanks

**Comment by avershave** [comment]
I'm lost. I added those annotations to the Ingress and it looks exactly the same. I'm getting a 404 for the css/js. So it would be <hostname>/styles.css?2c75d4b8b4afbd0eb1d0 but are ACTUALLY located at <hostname>/longhorn/styles.css?2c75d4b8b4afbd0eb1d0. I assume it's not the annotations/Ingress but a pod setting to enable pathed routing? Currently using 1.3.2.

**Comment by smallteeths** [comment]
Don't leave out `/`, the correct url path should be `http://xxx.xxx.xxx.xxx/longhorn/` @avershave .  If this still not work, , please post the ingress.yaml, thanks.

**Comment by Dubouchj** [comment]
Here is my full ingress with subpath and it works with the "/" at the end of my URL "https://mon-domaine/longhorn/"

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        path: /longhorn(/|$)(.*)
        pathType: Prefix
```

**Comment by anonymouspage** [comment]
@Dubouchj Which version of longhorn are you running? I've still had no luck with this issue -- tried your configuration and still no dice.

**Comment by Dubouchj** [comment]
@anonymouspage I use version 1.3.2

**Comment by anonymouspage** [comment]
@Dubouchj I guess it would help if I targeted the right ingress controller. 🤦🏻‍♂️

For those using k3s and/or traefik, you might have more luck with something like the following. Change the host (and pathprefix) as needed.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rewrite-longhorn-dashboard
  namespace: longhorn-system
spec:
  replacePathRegex:
    regex: ^/longhorn(/|$)(.*)
    replacement: /$2
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host("k3s") && PathPrefix("/longhorn")
      kind: Rule
      services:
        - name: longhorn-frontend
          namespace: longhorn-system
          port: 80
      middlewares:
        - name: rewrite-longhorn-dashboard
```

**Comment by anonymouspage** [comment]
@HShamimGEHC  If you aren't using traefik the example above will not work -- it is specific to traefik's API. You will need to craft something for whichever ingress controller you are using.

**Comment by ptisma** [comment]
`apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: replacepath
  namespace: longhorn-system
spec:
 replacePathRegex:
    regex: "^/longhorn(/|$)(.*)"
    replacement: "/${2}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-stage"
    traefik.ingress.kubernetes.io/router.middlewares: "longhorn-system-replacepath@kubernetescrd,longhorn-system-my-auth-middleware@kubernetescrd"
  name: longhorn
  namespace: longhorn-system
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - test.xyz
    secretName:test-xyz-tls
  rules:
  - host: test.xyz
    http:
      paths:
        - pathType: Prefix
          path: /longhorn
          backend:
            service:
              name: longhorn-frontend
              port:
                number: 80`

 I am facing the same issue, if I put the path /longhorn I just get a blank white page, but if I put the /longhorn/, it works, but it should work as well with the  /longhorn due to regex replacement, can someone explain me why is this happening?

**Comment by morooshka** [comment]
@ptisma, It also looks strange for me, should work
But this version work both for ending slashes and without and feets to the task better:
~~~
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rewrite-longhorn-prefix-middleware
  namespace: longhorn
spec:
  stripPrefixRegex:
    regex:
      - "^/longhorn/?"
~~~

**Comment by gillwong** [comment]
Got it working with Traefik's ingress controller by adding a RedirectRegex middleware before the ReplacePathRegex middleware:
```yaml
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-noslash
  namespace: longhorn-system
spec:
  redirectRegex:
    permanent: true
    regex: ^(https?://[^/]+/longhorn)$
    replacement: ${1}/
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: replacepath-longhorn-ui
  namespace: longhorn-system
spec:
  replacePathRegex:
    regex: ^/longhorn/(.*)
    replacement: /${1}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-redirect-noslash@kubernetescrd,longhorn-system-replacepath-longhorn-ui@kubernetescrd
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  ingressClassName: traefik
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        path: /longhorn
        pathType: Prefix
```
[Ref](https://community.traefik.io/t/middleware-to-add-the-if-needed/1895/19)

**Comment by armeldemarsac92** [comment]
has anyone tried to get it working with the new gateway api definitions ? Trying to setup up an httproute with kong to serve the ui under a subpath to no avail.

**Comment by armeldemarsac92** [comment]
Got it working with kong and the newer gatewayapi crds.

```                                                                                                       
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-longhorn
  namespace: monitoring
spec:
  parentRefs:
  - name: monitoring-gateway
    namespace: monitoring
    sectionName: https-global
  rules:
  - matches: 
    - path:
        type: PathPrefix
        value: "/longhorn/"
    
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    
    backendRefs: 
    - name: longhorn-frontend
      kind: Service
      port: 80
      namespace: longhorn-system

```

**Comment by andrei-don** [comment]
The URLRewrite filter did the trick for me, thank you @armeldemarsac92 👌
