### ISSUE TITLE
[BUG] Faulted volume when node crashes (non replicated volumes)

### ISSUE THREAD

**Issue by amadub** [longhorn/longhorn#3670]
## Describe the bug

When running a statefulset using a rwo, non-replicated volume the volumes will become faulted and cannot recovery unless manual intervention is applied. 

When a node goes down and a new node is spun up, the statefulset pod will be re-created but cannot use the volume and has the following error:

`Warning  FailedAttachVolume  19m                 attachdetach-controller  Multi-Attach error for volume "pvc-353f7cbe-b518-469e-879c-52987c8a83d1" Volume is already exclusively attached to one node and can't be attached to another`

I can manually delete the faulted volume through the UI and re-create the statefulset pod, but would hope there is a better solution than going this route.

Also note, This issue does not exist if I have replication turned on in longhorn, but that is not an ideal fix for my current application. 

## Environment
 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3

**Comment by derekbit** [comment]
@amadub 
Did you try this https://longhorn.io/docs/1.2.3/high-availability/node-failure/#longhorn-pod-deletion-policy-when-node-is-down?
This issue is related to `Pod Deletion Policy When Node is Down` and you can set it to `delete-both-statefulset-and-deployment-pod`.

**Comment by amadub** [comment]
@derekbit

Thanks for the response! 

Yeah, that setting is already set to `delete-both-statefulset-and-deployment-pod`

**Comment by derekbit** [comment]
> Also note, This issue does not exist if I have replication turned on in longhorn, but that is not an ideal fix for my current application.
@amadub 
So, you was using the volume with single replica, correct?

**Comment by amadub** [comment]
@derekbit 

Yeah, that's correct. Also, here are the remainder of my settings:

```
NAME                                                 VALUE
allow-node-drain-with-last-healthy-replica           true
allow-recurring-job-while-volume-detached            false
allow-volume-creation-with-degraded-availability     true
auto-cleanup-system-generated-snapshot               true
auto-delete-pod-when-volume-detached-unexpectedly    true
auto-salvage                                         true
backing-image-cleanup-wait-interval                  6
backing-image-recovery-wait-interval                 300
backup-target
backup-target-credential-secret
backupstore-poll-interval                            300
concurrent-automatic-engine-upgrade-per-node-limit   0
concurrent-replica-rebuild-per-node-limit            5
crd-api-version                                      longhorn.io/v1beta1
create-default-disk-labeled-nodes                    false
default-backing-image-manager-image
default-data-locality                                best-effort
default-data-path                                    /data/longhorn
default-engine-image                                 longhornio/longhorn-engine:v1.2.3
default-instance-manager-image                       longhornio/longhorn-instance-manager:v1_20211210
default-longhorn-static-storage-class                longhorn-static
default-replica-count                                3
default-share-manager-image                          longhornio/longhorn-share-manager:v1_20211020
disable-replica-rebuild                              false
disable-revision-counter                             false
disable-scheduling-on-cordoned-node                  true
guaranteed-engine-cpu
guaranteed-engine-manager-cpu                        12
guaranteed-replica-manager-cpu                       12
latest-longhorn-version                              v1.2.3
mkfs-ext4-parameters
node-down-pod-deletion-policy                        delete-both-statefulset-and-deployment-pod
priority-class
registry-secret
replica-auto-balance                                 best-effort
replica-replenishment-wait-interval                  600
replica-soft-anti-affinity                           true
replica-zone-soft-anti-affinity                      true
stable-longhorn-versions                             v1.0.2,v1.1.3,v1.2.3
storage-minimal-available-percentage                 25
storage-over-provisioning-percentage                 200
system-managed-components-node-selector
system-managed-pods-image-pull-policy                if-not-present
taint-toleration
upgrade-checker                                      true
volume-attachment-recovery-policy                    immediate
```

**Comment by amadub** [comment]
@derekbit 

Don't mean to spam you, but I believe the issue could be related to the PV & PVC not being removed after a node crashes. The pod is getting re-created but the PV & PVC remain. I can remove them when I delete the faulted volume in longhorn.. but am trying to get this to happen without manual intervention.

**Comment by derekbit** [comment]
@derekbit 
For the volume with single replica, if the replica is on the down node, Longhorn cannot restart the volume on another node automatically. Manual intervention is necessary in this case.
If you would like to rescue the data in the down node, you need do backup restore on another node.

**Comment by innobead** [comment]
> For the volume with single replica, if the replica is on the down node, Longhorn cannot restart the volume on another node automatically. Manual intervention is necessary in this case. If you would like to rescue the data in the down node, you need do backup restore on another node.

Probably should consider how to improve user experience in this case, ref: #3957

**Comment by zestyrahul** [comment]
Hi, is this issue resolved in any of the new release like 1.4.0 ?

We are expecting the POD to come up with new PV if old PV is not available after some time due to node being down. But right now Pod is trying to old PV claim and requires manual intervention 

We are using single replica count.

**Comment by innobead** [comment]
> Hi, is this issue resolved in any of the new release like 1.4.0 ?
> 
> 
> 
> We are expecting the POD to come up with new PV if old PV is not available after some time due to node being down. But right now Pod is trying to old PV claim and requires manual intervention 
> 
> 
> 
> We are using single replica count.

That's because the PVC is retained   to reuse, so even the terminating pod has been deleted and recreated, it's still unable to attach the volume successfully if the volume is 1 replica and stored in the down node as well.

We have an improvement for this case in 1.2.5 but only when the replica number is more than 1. https://github.com/longhorn/longhorn/issues/2947

At upstream, there is alpha feature https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/, but unfortunately it's only focusing on the statefulset instead of individual pod.

I believe what u want is automatically delete the retained PVC when the volume has one replica, and let it be recreated when the terminating pod is recreated.
