### ISSUE TITLE
[BUG] Helm uninstall stuck

### ISSUE THREAD

**Issue by dyipon** [longhorn/longhorn#3848]
## Describe the bug

Longhorn helm chart uninstall can't remove longhorn-ui deployment

## To Reproduce

1. helm install longhorn
2. helm uninstall longhorn
3. uninstall can't remove UI deploy, the uninstall process stuck

## Expected behavior

Should remove the UI deployment, and finish the whole uninstall process.

## Environment

 - Longhorn version:  1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.23.4
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 8
 - Node config
   - OS type and version: debian
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 1

**Comment by kaxing** [comment]
Hi @dyipon did you use any parameters with your helm installation?

Attaching my command history for reference:
```
$ helm repo add longhorn https://charts.longhorn.io
$ helm repo update
$ helm install longhorn longhorn/longhorn -n longhorn-system --create-namespace
# Open Longhorn UI via nodeport
# Create volume from the UI
$ helm uninstall longhorn -n longhorn-system
```

**Comment by dyipon** [comment]
@kaxing I tried your commands, and works fine, but i don't know why my settings cause uninstall issues.
Here are my values, nothing special I just setup a backuptarget on installing:


- defaultSettings.backupTarget: s3://longhorn@us-east-1/
- defaultSettings.backupTargetCredentialSecret: minio-longhorn
- defaultSettings.allowRecurringJobWhileVolumeDetached: true

**Comment by reddybhavaniprasad** [comment]
I am also facing the same issue on RKE2. I have deployed longhorn 1.2.4 on RKE2 and the longhorn-manager pods are stuck in **CrashLoopBackOff** state.

**Longhorn Installation using helm:**
```
helm install -f longhorn/values.yaml longhorn/ --generate-name
```

**longhorn uninstallation using helm:**
```
helm uninstall  longhorn-1665382587
```

Pod are not in **Running** state,
```
[kubenode@master ~]$ kubectl get all -n longhorn-system
NAME                                            READY   STATUS             RESTARTS         AGE
pod/longhorn-driver-deployer-78985f4cf7-x69sh   0/1     Init:0/1           0                8h
pod/longhorn-manager-f4954                      0/1     CrashLoopBackOff   99 (4m21s ago)   8h
pod/longhorn-manager-gmfqx                      0/1     CrashLoopBackOff   99 (2m35s ago)   8h
pod/longhorn-manager-lfmwq                      0/1     CrashLoopBackOff   99 (3m25s ago)   8h
pod/longhorn-manager-mr92d                      0/1     CrashLoopBackOff   99 (3m7s ago)    8h
pod/longhorn-manager-qldq4                      0/1     CrashLoopBackOff   99 (4m ago)      8h
pod/longhorn-manager-sggpx                      0/1     CrashLoopBackOff   99 (3m25s ago)   8h
pod/longhorn-manager-tgxfw                      0/1     CrashLoopBackOff   99 (4m20s ago)   8h
pod/longhorn-ui-65d698b889-fh94t                1/1     Running            0                8h
pod/longhorn-uninstall-wpfc8                    1/1     Running            0                107s

NAME                               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/longhorn-backend           ClusterIP   10.43.69.42   <none>        9500/TCP   8h
service/longhorn-engine-manager    ClusterIP   None          <none>        <none>     8h
service/longhorn-frontend          ClusterIP   10.43.44.77   <none>        80/TCP     8h
service/longhorn-replica-manager   ClusterIP   None          <none>        <none>     8h

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/longhorn-manager   7         7         0       7            0           <none>          8h

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/longhorn-driver-deployer   0/1     1            0           8h
deployment.apps/longhorn-ui                1/1     1            1           8h

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/longhorn-driver-deployer-78985f4cf7   1         1         0       8h
replicaset.apps/longhorn-ui-65d698b889                1         1         1       8h

NAME                           COMPLETIONS   DURATION   AGE
job.batch/longhorn-uninstall   0/1           107s       107s
```

**Comment by devgig** [comment]
Same issue with v1.4.  Had over 300 restarts on the csi plugin and could not uninstall.  Set all deployments to 0 replica and daemonsets to 0, still no luck.  Keeps on timing out.  Prefer to not manually delete if I can avoid it.

**Comment by jfmatth** [comment]
I had a similar issue, and noticed all the uninstall pods had errors with 

```
$ k logs longhorn-uninstall-dqw4s -n longhorn-system
W0204 15:00:11.044194       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0204 15:00:12.252485       1 shared_informer.go:240] Waiting for caches to sync for longhorn uninstall
I0204 15:00:13.453485       1 request.go:665] Waited for 1.196222513s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/longhorn.io/v1beta2/snapshots?limit=500&resourceVersion=0
I0204 15:00:14.353495       1 shared_informer.go:247] Caches are synced for longhorn uninstall
time="2023-02-04T15:00:14Z" level=fatal msg="cannot uninstall Longhorn because deleting-confirmation-flag is set to `false`. Please set it to `true` using Longhorn UI or kubectl -n longhorn-system edit settings.longhorn.io deleting-confirmation-flag "
```

After running the edit, it worked.

**Comment by ebCrypto** [comment]
thank you @jfmatth ran into the same problem. I am confirming that running the suggested command by the logs in the uninstall pod worked

**Comment by sajjadG** [comment]
For me longhorn is stuck in installing, it can't get the images from our private registry, so when trying to uninstall it creates `longhorn-uninstall-wknpl` pod which stuck in getting the image from private registry too. So not installing and not uninstalling.

**Comment by jfmatth** [comment]
you tried my advice above?  I haven't used it in the newest version, but that above always worked for me

**Comment by sajjadG** [comment]
> you tried my advice above? I haven't used it in the newest version, but that above always worked for me

Yes I tried your advice. But it did not work for me.

**Comment by przemas75** [comment]
For 1.4.2 i dont see that setting 'deleting-confirmation-flag'...
`❯ kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag
Error from server (NotFound): settings.longhorn.io "deleting-confirmation-flag" not found`

Installed from helm.

**Comment by przemas75** [comment]
Done that also, edit is with no failure, but my change has no effect.
Once again editing shows there was no stanza previously inserted...

**Comment by c3y1huang** [comment]
This issue is old and the info might no longhorn be relevant. Please create a new issue when encountering this issue again, providing environment details, and the steps to reproduce.
