### ISSUE TITLE
[BUG]  timeouts during volume attach/reattach operations

### ISSUE THREAD

**Issue by gothka** [longhorn/longhorn#4798]
## Describe the bug
We've been using RWX volumes in production for few months now. Lately, we are running into the issue where the volumes couldn't be attached or reattached to the statefulset workloads cause of timeouts & mounting failures which is kinda leading to cascading failures. And unavailable to perform maintenance on those nodes.

```
0s          Warning   FailedAttachVolume      pod/redis-0                            AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-35-89.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/mongodb-0                          AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-55-126.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/redis-0                            AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-35-89.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/mongodb-0                          AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-55-126.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/redis-0                            AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-35-89.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/mongodb-0                          AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-55-126.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/redis-0                            AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-35-89.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/mongodb-0                          AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-55-126.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/redis-0                            AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-35-89.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/mongodb-0                          AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-55-126.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/redis-0                            AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-35-89.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/mongodb-0                          AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-55-126.eu-west-1.compute.internal
1s          Warning   FailedMount             pod/mongodb-0                          Unable to attach or mount volumes: unmounted volumes=[pvc], unattached volumes=[pvc kube-api-access-k6tvx]: timed out waiting for the condition
0s          Warning   FailedMount             pod/redis-0                            Unable to attach or mount volumes: unmounted volumes=[pvc], unattached volumes=[redis-conf kube-api-access-jmdsr pvc]: timed out waiting for the condition
0s          Warning   FailedAttachVolume      pod/redis-0                            AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-35-89.eu-west-1.compute.internal
0s          Warning   FailedAttachVolume      pod/mongodb-0                          AttachVolume.Attach failed for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6" : rpc error: code = DeadlineExceeded desc = volume pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6 failed to attach to node ip-10-8-55-126.eu-west-1.compute.internal
0s          Normal    SuccessfulAttachVolume   pod/tyk-redis-0                            AttachVolume.Attach succeeded for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6"
0s          Normal    SuccessfulAttachVolume   pod/tyk-mongodb-0                          AttachVolume.Attach succeeded for volume "pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6"
```
## To Reproduce

Run RWX volumes on a large cluster consisting of 50+ nodes and 500+ volumes

## Expected behavior

Volume attach/reattach should happen without any timeouts. I'm assuming the reattachment process is handled by k8s instead of longhorn 

## Log or Support bundle

Sent via email as it may contain some sensitive data that pertains to our environment

## Environment

 - Longhorn version: v1.2.5
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS
   - Number of management node in the cluster: 5
   - Number of worker node in the cluster: 50+
 - Node config
   - OS type and version: AL2
   - CPU per node: 4/8
   - Memory per node: 16/18
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): EKS
 - Number of Longhorn volumes in the cluster: 500+

## Additional context

May not be related to this directly but we have been running into #4789 too on the cluster. After kinda resolving the #4789  some of the volume provisioning is successful now. Generally, it takes 2mins or less for volume to be provisioned and attached to the statefulset workload, but currently its taking 4+ minutes to do the same operations without too many timeouts and mount failures.

**Comment by joshimoo** [comment]
What is your reason for running redis/mongodb on top of a RWX volume?

Have you considered using regular RWO volumes for these workloads?

**Comment by PhanLe1010** [comment]
@abhishiekgowtham 

I cannot seem to find the log error message in the support bundle. In the support bundle, looks like the volume is perfectly healthy:
```
  status:
    ownerid: ip-10-5-105-228.eu-west-1.compute.internal
    state: attached
    robustness: healthy
    lastdegradedat: ""
    shareendpoint: nfs://172.20.84.151/pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6
    sharestate: running
```

Do you mean that the issue is it take long time for the volume to attach (more than 4 mins) ?

**Comment by abhishiekgowtham** [comment]
> What is your reason for running redis/mongodb on top of a RWX volume?
> 
> Have you considered using regular RWO volumes for these workloads?

We have a niche use case for this cluster where we need to use RWX volumes because of sheer amount of data/volumes that we have to manage and some cost savings. Using RWO isn't an option for us at this point. We had given it a try but didn't fully satisfy our requirements.

**Comment by abhishiekgowtham** [comment]
> @abhishiekgowtham
> 
> I cannot seem to find the log error message in the support bundle. In the support bundle, looks like the volume is perfectly healthy:
> 
> ```
>   status:
>     ownerid: ip-10-5-105-228.eu-west-1.compute.internal
>     state: attached
>     robustness: healthy
>     lastdegradedat: ""
>     shareendpoint: nfs://172.20.84.151/pvc-ddd6c6cb-cca0-49e9-b654-a51abd03aac6
>     sharestate: running
> ```
> 
> Do you mean that the issue is it take long time for the volume to attach (more than 4 mins) ?

@PhanLe1010 kinda yes, the issue is that volumes are stuck when attaching (could be a newly provisioned one or existing one that was reattaching) and take longer time for the mounting to be done and allow statefulset to be in running state. To be specific, we have a condition where we don't allow attach/reattch operations to take more than 5 minutes.

**Comment by PhanLe1010** [comment]
This error `timed out waiting for the condition` usually happen when the share manager pod is not ready yet. Maybe it should go away when https://github.com/longhorn/longhorn/issues/4789 is fixed? Can you give it a try with the fix image of https://github.com/longhorn/longhorn/issues/4789?

**Comment by shuo-wu** [comment]
I just checked the support bundle.
It seems that the long mount issue happened at `2022-10-29T03:51:09Z` to `2022-10-29T06:32:56Z`. The error logs in the longhorn-csi-plugin (which is responsible for attaching and mounting) are mainly like:
```
2022-10-29T03:55:58.145942165Z time="2022-10-29T03:55:58Z" level=error msg="NodeGetVolumeStats: req: {\"volume_id\":\"pvc-0141dd6a-c464-4109-98e4-1d7db872730e\",\"volume_path\":\"/var/lib/kubelet/pods/64b099ca-0bfd-4316-a1d2-292192b9c205/volumes/kubernetes.io~csi/pvc-0141dd6a-c464-4109-98e4-1d7db872730e/mount\"} err: rpc error: code = Internal desc = failed to check volume mode for volume path /var/lib/kubelet/pods/64b099ca-0bfd-4316-a1d2-292192b9c205/volumes/kubernetes.io~csi/pvc-0141dd6a-c464-4109-98e4-1d7db872730e/mount: input/output error"
2022-10-29T03:57:33.335949526Z time="2022-10-29T03:57:33Z" level=error msg="NodeGetVolumeStats: req: {\"volume_id\":\"pvc-bd11440b-11c1-4bea-9d01-fcd47d4b2719\",\"volume_path\":\"/var/lib/kubelet/pods/71fef63b-4908-41f9-8fc4-47359a486ec5/volumes/kubernetes.io~csi/pvc-bd11440b-11c1-4bea-9d01-fcd47d4b2719/mount\"} err: rpc error: code = Internal desc = failed to check volume mode for volume path /var/lib/kubelet/pods/71fef63b-4908-41f9-8fc4-47359a486ec5/volumes/kubernetes.io~csi/pvc-bd11440b-11c1-4bea-9d01-fcd47d4b2719/mount: input/output error"
......
```

Notice that most of the longhorn-manager pods and instance-manager pods were restarted after `2022-10-31`. I don't know what happened at that moment... I guess there was something wrong then it lead to Longhorn components restart...

**Comment by abhishiekgowtham** [comment]
> This error `timed out waiting for the condition` usually happen when the share manager pod is not ready yet. Maybe it should go away when #4789 is fixed? Can you give it a try with the fix image of #4789?

after fixing #4789 this issue kinda went away (a bit faster than it was before) for newly provisioned volumes. Still seeing this behaviour on existing volumes that are on the cluster.

**Comment by abhishiekgowtham** [comment]
> I just checked the support bundle. It seems that the long mount issue happened at `2022-10-29T03:51:09Z` to `2022-10-29T06:32:56Z`. The error logs in the longhorn-csi-plugin (which is responsible for attaching and mounting) are mainly like:
> 
> ```
> 2022-10-29T03:55:58.145942165Z time="2022-10-29T03:55:58Z" level=error msg="NodeGetVolumeStats: req: {\"volume_id\":\"pvc-0141dd6a-c464-4109-98e4-1d7db872730e\",\"volume_path\":\"/var/lib/kubelet/pods/64b099ca-0bfd-4316-a1d2-292192b9c205/volumes/kubernetes.io~csi/pvc-0141dd6a-c464-4109-98e4-1d7db872730e/mount\"} err: rpc error: code = Internal desc = failed to check volume mode for volume path /var/lib/kubelet/pods/64b099ca-0bfd-4316-a1d2-292192b9c205/volumes/kubernetes.io~csi/pvc-0141dd6a-c464-4109-98e4-1d7db872730e/mount: input/output error"
> 2022-10-29T03:57:33.335949526Z time="2022-10-29T03:57:33Z" level=error msg="NodeGetVolumeStats: req: {\"volume_id\":\"pvc-bd11440b-11c1-4bea-9d01-fcd47d4b2719\",\"volume_path\":\"/var/lib/kubelet/pods/71fef63b-4908-41f9-8fc4-47359a486ec5/volumes/kubernetes.io~csi/pvc-bd11440b-11c1-4bea-9d01-fcd47d4b2719/mount\"} err: rpc error: code = Internal desc = failed to check volume mode for volume path /var/lib/kubelet/pods/71fef63b-4908-41f9-8fc4-47359a486ec5/volumes/kubernetes.io~csi/pvc-bd11440b-11c1-4bea-9d01-fcd47d4b2719/mount: input/output error"
> ......
> ```
> 
> Notice that most of the longhorn-manager pods and instance-manager pods were restarted after `2022-10-31`. I don't know what happened at that moment... I guess there was something wrong then it lead to Longhorn components restart...

IIRC, I think we may have restarted the longhorn-manager pods manually. We had priorityclass setting configured which lead to `instance-manager-e-xxxx` pods unable to scheduled on nodes and sometimes were being randomly deleted so had to remove the setting which was fine afterwards. Also, increased the (guaranteed) cpu resources which caused the instance-manager and longhorn-manager pods to restart.

**Comment by derekbit** [comment]
v1.2.5 is EOL. Feel free to reopen or create a ticket for the issue if it is valid in newer versions.
