### ISSUE TITLE
[TEST] Air gap pipeline fail at download support bundle when install method was helm chart

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5501]
## What's the test to develop? Please describe

Running air gap installation pipeline with `LONGHORN_INSTALL_METHOD` = `helm-chart`, the installation success but stuck at download support bundle. (Didn't encounter this problem when select `manifest-file` to install )

In local air gap environment, install Longhorn by helm chart, the support bundle downloaded success. 

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Have consistent result

## Additional context

[master head](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3127/console) result
[v1.4.1-rc2](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3125/parameters/) result

**Comment by innobead** [comment]
@c3y1huang Could you help check with @chriscchien ? Thanks.

**Comment by innobead** [comment]
cc @yangchiu

**Comment by c3y1huang** [comment]
> In local air gap environment, install Longhorn by helm chart, the support bundle downloaded success.

@chriscchien , are you able to access the cluster to see if there are any errors?

**Comment by chriscchien** [comment]
> > In local air gap environment, install Longhorn by helm chart, the support bundle downloaded success.
> 
> @chriscchien , are you able to access the cluster to see if there are any clues?

I can not access pipeline cluster

**Comment by c3y1huang** [comment]
> I can not access pipeline cluster

@yangchiu , I am not sure if this is related to the pipeline, are you able to access the cluster and see if there are any clues?

**Comment by innobead** [comment]
If the local testing working fine, that could be related to the infra issue. This can be revisited later, low priority for now.

**Comment by c3y1huang** [comment]
Ref: https://github.com/longhorn/longhorn-tests/blob/master/test_framework/scripts/longhorn-setup.sh#L134-L152

**Comment by innobead** [comment]
Let's revisit this after https://github.com/longhorn/longhorn/issues/5614 is resolved. 

cc @c3y1huang @yangchiu

**Comment by innobead** [comment]
@c3y1huang is this still valid?

**Comment by yangchiu** [comment]
Unfortunately, this issue still presents in master-head: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3670/.

The support-bundle-kit image is unable to be pulled:
```
# kubectl get pods -n longhorn-system
longhorn-support-bundle-manager-support-bundle-2023-05-03tltgjt   0/1     ErrImagePull   0          16m
# kubectl describe pod longhorn-support-bundle-manager-support-bundle-2023-05-03tltgjt -n longhorn-system
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  17m                  default-scheduler  Successfully assigned longhorn-system/longhorn-support-bundle-manager-support-bundle-2023-05-03tltgjt to ip-10-0-2-64
  Normal   Pulling    15m (x4 over 17m)    kubelet            Pulling image "lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24"
  Warning  Failed     15m (x4 over 17m)    kubelet            Failed to pull image "lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24": rpc error: code = Unknown desc = failed to pull and unpack image "lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24": failed to resolve reference "lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24": pulling from host lh-registry-qzzri4r6.ci-qa.rancher.space failed with status code [manifests v0.0.24]: 401 Unauthorized
  Warning  Failed     15m (x4 over 17m)    kubelet            Error: ErrImagePull
  Warning  Failed     15m (x6 over 17m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    116s (x66 over 17m)  kubelet            Back-off pulling image "lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24"
```
But the image exists on the private registry for sure:
```
$ docker pull lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24
v0.0.24: Pulling from longhornio/support-bundle-kit
Digest: sha256:7545a151aeea1653423a81cbf3fd01c8a50d4b42528833a280ddd7aeb5e7cba1
Status: Downloaded newer image for lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24
lh-registry-qzzri4r6.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.24
```

**Comment by innobead** [comment]
I see. Thanks @yangchiu . :+1:

**Comment by yangchiu** [comment]
Verified passed by running the helm chart air-gap test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3709/
