### ISSUE TITLE
[BUG] Some links in searching result of the official document are broken

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8024]
## Describe the bug

Some links in searching result are broken after reorganizing the document.
To fix the issue, probably need to reindex the document.

![image](https://github.com/longhorn/longhorn/assets/12527233/03b921c0-657e-4739-b523-41f540fb8592)

cc @innobead @mantissahz 

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by mantissahz** [comment]
Found some crawling errors in Algolia crawler, and re-running crawling now.

**Comment by mantissahz** [comment]
After recrawling and reindexing with the Algolia, it should be working well now.

**Comment by mantissahz** [comment]
The broken links can be found by searching trim with the versions v1.6.0, v1.6.1, and v1.7.0 such as https://longhorn.io/docs/1.6.0/volumes-and-nodes/trim-filesystem/#prerequisites .
Now it is normal as https://longhorn.io/docs/1.6.0/nodes-and-volumes/volumes/trim-filesystem/#trim-the-filesystem-in-a-longhorn-volume.

It got the broken links because we changed the directory name from `volumes-and-nodes` at v1.6.0 to `nodes-and-volumes` and recrawling was not triggered.

**Comment by innobead** [comment]
Accessing https://longhorn.io/docs/1.6.0/volumes-and-nodes/trim-filesystem/#prerequisites, still not found?

**Comment by mantissahz** [comment]
>Accessing https://longhorn.io/docs/1.6.0/volumes-and-nodes/trim-filesystem/#prerequisites, still not found?

That's an example of the broken link.
And now when the users search the keyword `trim` on https://longhorn.io, the users will get the right link https://longhorn.io/docs/1.6.0/nodes-and-volumes/volumes/trim-filesystem/#prerequisites.

**Comment by innobead** [comment]
Oh I see. Thanks for the explanation.
