### ISSUE TITLE
[BUG] Volume Attachment is being deleted - daily occurrence on v1.7.2

### ISSUE THREAD

**Issue by voarsh2** [longhorn/longhorn#9934]
## Describe the bug

Worker nodes may become memory constrained, or non-responsive and Kubelet kills all the pods.
Prior to this version, I didn't face issues of having to remove the finalizer of the VolumeAttachment object for PVC's.

To be clear, this was not happening on the prior version of v1.7.2

## To Reproduce

Have nodes become in state "Kubelet stopped posting status" on Longhorn v1.7.2, you're likely to run into this.

## Expected behavior

VolumeAttachment object for the PVC cleaned up properly.

## Environment

 - Longhorn version: v1.7.2
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 - 1.26.x
   - Number of control plane nodes in the cluster: 5
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 22 LTS
   - Kernel version:
   - CPU per node: 6-12 - variable
   - Memory per node: 50GB + variable
   - Disk type (e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 30ish

**Comment by innobead** [comment]
Do you mean pods were killed but VAs were leftover? BTW, please provide the support bundle as well. Thanks.

**Comment by voarsh2** [comment]
> Do you mean pods were killed but VAs were leftover? BTW, please provide the support bundle as well. Thanks.

Bundle done.

I mean, as per how Kubelet works, if there is memory pressure, ETCD being too slow, or whatever, Kubelet status is not healthy, node is marked as unavailable, after 5 minutes pods are in terminating state.

On 1.7.2, I am frequently having to manually remove finalizer on the VA object to get PVC's started again - especially annoying with Statefulsets with x3 pods for redundancy and I have to baby-sit it (e.g DB cluster can't start if pod won't start because PVC can't be used).

**Comment by ChanYiLin** [comment]
From longhorn-csi-plugin, it also failed to unpublish the volume, investigating.
```
2024-12-09T07:55:19.740535201Z time="2024-12-09T07:55:19Z" level=warning msg="Timeout while waiting for volume pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9 state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
2024-12-09T07:55:19.740612343Z time="2024-12-09T07:55:19Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9 from node worker2" func=csi.logGRPC file="server.go:136"
2024-12-09T07:55:19.771660997Z time="2024-12-09T07:55:19Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"worker2\",\"volume_id\":\"pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9\"}" func=csi.logGRPC file="server.go:130"
2024-12-09T07:55:19.771728278Z time="2024-12-09T07:55:19Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9\" node_id:\"worker2\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
2024-12-09T07:55:19.798057374Z time="2024-12-09T07:55:19Z" level=info msg="Requesting volume pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9 detachment for node worker2 with attachmentID csi-de38785b61a0101cd1449be6f9c11f4a387f73621f258c5567c3c33610ffafcb " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
2024-12-09T07:56:49.853390093Z time="2024-12-09T07:56:49Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9 from node worker2" func=csi.logGRPC file="server.go:136"
2024-12-09T07:56:49.879702429Z time="2024-12-09T07:56:49Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"worker2\",\"volume_id\":\"pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9\"}" func=csi.logGRPC file="server.go:130"
2024-12-09T07:56:49.879753850Z time="2024-12-09T07:56:49Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9\" node_id:\"worker2\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
2024-12-09T07:56:49.888598848Z time="2024-12-09T07:56:49Z" level=info msg="Requesting volume pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9 detachment for node worker2 with attachmentID csi-de38785b61a0101cd1449be6f9c11f4a387f73621f258c5567c3c33610ffafcb " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
```

**Comment by ChanYiLin** [comment]
Hi @voarsh2 
It seems the yaml files are missing from the support bundle
We will need those Longhorn CR yamls to know the current status of the resources
You can send the full support bundle to this email, longhorn-support-bundle@suse.com, to avoid security issue.
Thanks

**Comment by ChanYiLin** [comment]
![Screenshot from 2024-12-09 16-58-21](https://github.com/user-attachments/assets/d39cf634-0d7f-4591-ab39-b57e01030bb6)

Support bundle should have a folder called `"yaml"` including all the resources yaml, so we can check the spec and status of the volume and other resources, like the `volumeAttachment` yaml you provided.
The error seems not related to the issue.
Can you regenerate the support bundle again?

**Comment by ChanYiLin** [comment]
Have you already fixed the cluster by manually removing the finalizer?
And the pod and volume are currently running correctly?

If yes, then the yaml already loses the information when the issue happened.
Let me discuss internally with other team members to see if we can get some insights from the logs.

If this happens again, can you help me to collect the information of the following yamls
- `kubectl get lhva -n longhorn-system -oyaml`
- `kubectl get lhv -n longhorn-system -oyaml`
- `kubectl get lhe -n longhorn-system -oyaml`
- `kubectl get lhr -n longhorn-system -oyaml`
- `kubectl get lhim -n longhorn-system -oyaml`

Thanks

**Comment by voarsh2** [comment]
> Have you already fixed the cluster by manually removing the finalizer? And the pod and volume are currently running correctly?
> 
> If yes, then the yaml already loses the information of the issue. Let me discuss internally with other team members to see if we can get some insights from the logs.
> 
> If this happens again, can you help me to collect the information of the following yamls
> 
> * `kubectl get lhva -n longhorn-system -oyaml`
> * `kubectl get lhv -n longhorn-system -oyaml`
> * `kubectl get lhe -n longhorn-system -oyaml`
> * `kubectl get lhr -n longhorn-system -oyaml`
> * `kubectl get lhim -n longhorn-system -oyaml`
> 
> Thanks

Sure.
I'm sure it'll happen today or so and I'll try and get these for you while it is happening and before I remove the finalizer.
Thanks.

**Comment by ChanYiLin** [comment]
And also generate the support bundle for the logs
thanks!

**Comment by ChanYiLin** [comment]
@PhanLe1010 
If you are available, could you also help to take a look on this issue?
Thanks

**Comment by DHandspikerWade** [comment]
I've also been having this issue for about a month after I upgraded to 1.7.2.  Whenever a statefulset pod get preempted, the volume get stuck in a running state attached unable to move to another node. 

I've been following https://github.com/longhorn/longhorn/issues/9781#issuecomment-2468059440 believing it to be related.

**Comment by voarsh2** [comment]
> I've also been having this issue for about a month after I upgraded to 1.7.2. Whenever a statefulset pod get preempted, the volume get stuck in a running state attached unable to move to another node.
> 
> I've been following [#9781 (comment)](https://github.com/longhorn/longhorn/issues/9781#issuecomment-2468059440) believing it to be related.

Glad it's not just me.

Can't say it's exactly the same issue though. Will leave it up to the LH team to decide what to do.
Might ask if you have any different logs than what I've provided.

**Comment by ChanYiLin** [comment]
@c3y1huang 
Can you help to verify if this is the same issue as https://github.com/longhorn/longhorn/issues/9781#issuecomment-2468059440 ?
Thanks

**Comment by derekbit** [comment]
cc @c3y1huang @PhanLe1010

**Comment by derekbit** [comment]
> @c3y1huang Can you help to verify if this is the same issue as [#9781 (comment)](https://github.com/longhorn/longhorn/issues/9781#issuecomment-2468059440) ? Thanks

@voarsh2 any update?

**Comment by c3y1huang** [comment]
> @c3y1huang Can you help to verify if this is the same issue as [#9781 (comment)](https://github.com/longhorn/longhorn/issues/9781#issuecomment-2468059440) ? Thanks

No, it doesn't seem to be having the same symptoms.

**Comment by c3y1huang** [comment]
@voarsh2 could you also share the Setting CRs?
```
k -n longhorn-system get setting -o yaml
```

**Comment by SNThrailkill** [comment]
im also seeing this problem happen frequently and its causing all of my workloads to just hang in the `ContainerCreating` stage. Been happening with all types of volumes for weeks. Im at my wits end. Happy to provide a support bundle if warranted. Here are some example logs from my longhorn pods when its in this state:

```
time="2025-01-02T05:20:28Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
time="2025-01-02T05:20:28Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
time="2025-01-02T05:18:57Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
time="2025-01-02T05:18:57Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
time="2025-01-02T05:18:57Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"k3s-worker-03\",\"volume_id\":\"example-volume\"}" func=csi.logGRPC file="server.go:130" time="2025-01-02T05:18:57Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
time="2025-01-02T05:18:57Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
time="2025-01-02T05:17:27Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
time="2025-01-02T05:17:27Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
time="2025-01-02T05:17:27Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"k3s-worker-03\",\"volume_id\":\"example-volume\"}" func=csi.logGRPC file="server.go:130"
time="2025-01-02T05:12:27Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
time="2025-01-02T05:12:27Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
time="2025-01-02T05:00:57Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
time="2025-01-02T05:00:57Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
time="2025-01-02T04:59:27Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
time="2025-01-02T04:59:27Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
time="2025-01-02T04:59:27Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"k3s-worker-03\",\"volume_id\":\"example-volume\"}" func=csi.logGRPC file="server.go:130"
time="2025-01-02T04:59:27Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
time="2025-01-02T04:59:27Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
time="2025-01-02T04:57:56Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
time="2025-01-02T04:57:56Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
```

**Comment by derekbit** [comment]
@c3y1huang Can you help investigate the issue?

**Comment by c3y1huang** [comment]
> im also seeing this problem happen frequently and its causing all of my workloads to just hang in the `ContainerCreating` stage. Been happening with all types of volumes for weeks. Im at my wits end. Usually I can fix it by force detaching the volume but that causes other issues. Happy to provide a support bundle if warranted. Here are some example logs from my longhorn pods when its in this state:
> 
> ```
> time="2025-01-02T05:20:28Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
> time="2025-01-02T05:20:28Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
> time="2025-01-02T05:18:57Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
> time="2025-01-02T05:18:57Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
> time="2025-01-02T05:18:57Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"k3s-worker-03\",\"volume_id\":\"example-volume\"}" func=csi.logGRPC file="server.go:130" time="2025-01-02T05:18:57Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
> time="2025-01-02T05:18:57Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
> time="2025-01-02T05:17:27Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
> time="2025-01-02T05:17:27Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
> time="2025-01-02T05:17:27Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"k3s-worker-03\",\"volume_id\":\"example-volume\"}" func=csi.logGRPC file="server.go:130"
> time="2025-01-02T05:12:27Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
> time="2025-01-02T05:12:27Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
> time="2025-01-02T05:00:57Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
> time="2025-01-02T05:00:57Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
> time="2025-01-02T04:59:27Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
> time="2025-01-02T04:59:27Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
> time="2025-01-02T04:59:27Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"k3s-worker-03\",\"volume_id\":\"example-volume\"}" func=csi.logGRPC file="server.go:130"
> time="2025-01-02T04:59:27Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = DeadlineExceeded desc = Failed to detach volume example-volume from node k3s-worker-03" func=csi.logGRPC file="server.go:136"
> time="2025-01-02T04:59:27Z" level=warning msg="Timeout while waiting for volume example-volume state volume unpublished" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:1192" component=csi-controller-server function=waitForVolumeState
> time="2025-01-02T04:57:56Z" level=info msg="Requesting volume example-volume detachment for node k3s-worker-03 with attachmentID csi-8968dc74ae25db674972f45113e0568a3c03f353aab475e88eb2b620799117f3 " func="csi.(*ControllerServer).unpublishVolume" file="controller_server.go:595" component=csi-controller-server function=unpublishVolume
> time="2025-01-02T04:57:56Z" level=info msg="ControllerUnpublishVolume is called with req volume_id:\"example-volume\" node_id:\"k3s-worker-03\" " func="csi.(*ControllerServer).ControllerUnpublishVolume" file="controller_server.go:550" component=csi-controller-server function=ControllerUnpublishVolume
> ```

@SNThrailkill , You can send the support bundle to longhorn-support-bundle@suse.com .

---

Could you provide some context about your cluster?
```
 - Longhorn version: 
 - Impacted volume (PV): <!-- PLEASE specify the volume name to better identify the cause -->
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
```

---

Have you observed this behavior with other Longhorn versions? If not, what was the most recent Longhorn version before encountering this issue?

**Comment by voarsh2** [comment]
> @voarsh2 Could you also share the Setting CRs?
> 
> ```
> k -n longhorn-system get setting -o yaml
> ```

Here you go 

[lh-settings.zip](https://github.com/user-attachments/files/18289402/lh-settings.zip)


> I noticed that the volume `pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9` is set to request a single volume replica `numberOfReplicas: 1`. However, there seem to be 3 replicas associated with this volume, with 2 in a stopped state:
> 
> * pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9-r-3f0ca382
> * pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9-r-5fe5730f
> * pvc-d99f2f7e-e191-454c-ba61-74077d68c2f9-r-bccc0d5e
> 
> Is this intentional?

This is probably a bug with LH... I only wanted 1 replica, since the underlying software has replication (clustered DB)

> 
> > Prior to this version, I didn't face issues of having to remove the finalizer of the VolumeAttachment object for PVC's.
> 
> What was your most recent Longhorn version before this? Was it v1.7.x (v1.7.0, 1.7.1) or v1.6.x?

Previous version would've been 1.7.1


> > Worker nodes may become memory constrained, or non-responsive and Kubelet kills all the pods.
> > Prior to this version, I didn't face issues of having to remove the finalizer of the VolumeAttachment object for PVC's.

> > On 1.7.2, I am frequently having to manually remove finalizer on the VA object to get PVC's started again
 
> Are you referring to the `volumeattachments.longhorn.io` or `volumeattachments.storage.k8s.io` VA? If it's the latter ( `volumeattachments.storage.k8s.io`), I'm not sure if this behavior could be related to upstream K8s, since the CSI components were updated in Longhorn v1.7.2. You could try using the `longhornio/csi-attacher:v4.6.1` to see if the issue persists.

Yes, I refer to 'volumeattachments.storage.k8s.io' VA. 
Clarify 'longhornio/csi-attacher:v4.6.1', try changing the csi image in the LH Helm Chart?

**Comment by SNThrailkill** [comment]
Support bundle sent. Answered the questions below as requested:
```
 - Longhorn version: 1.7.2
 - Impacted volume (PV): ghost-marisela-db, acid-matrix-0, acid-matrix-1 & more
 - Installation method: helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.27.4
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version: 5.15.0-130
   - CPU per node: 16 cores
   - Memory per node: 32 GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox
 - Number of Longhorn volumes in the cluster: ~30
 ```

**Comment by aep** [comment]
> not sure it was present with 1.7.1.

1.7.1 here. same issue. possibly related to snapshots, since it happens every night around that time. 

> Usually I can fix it by force detaching
> having to manually remove finalizer on the VA object 

none of these work. it just goes back into the same state. i have to delete the pvc and restore it from external backup every morning.

**Comment by derekbit** [comment]
@SNThrailkill @aep Can you provide the support bundles for your issues?

**Comment by derekbit** [comment]
cc @PhanLe1010

**Comment by SNThrailkill** [comment]
> @SNThrailkill @aep Can you provide the support bundles for your issues?

Already sent when requested on Jan 2nd

**Comment by derekbit** [comment]
@SNThrailkill Can you help create a BUG ticket for your case? Thanks.

**Comment by ChanYiLin** [comment]
@SNThrailkill From you logs we found two insights

1. Many of your daily backups created by the recurring job failed due to missing snapshots. We are still unsure why the snapshots were missing and will continue investigating.
    - Please also assist in checking if there is any other operation that might be deleting the snapshots at 00:00 when the daily recurring job starts.
2. As a result of point 1, the volume was automatically attached by Longhorn for the backup, but it wasn't detached because the backup remained in the "Pending" state due to the missing snapshot. This is why the volume stayed in the attached state.
    - To resolve this, we will introduce a maximum retry mechanism for the backup process to wait for the snapshot.

Please help us to open another issue and we can address these two points there as these might not be the same as this issue

cc @derekbit @c3y1huang

**Comment by PhanLe1010** [comment]
Hye @ChanYiLin I pushed the fix https://github.com/longhorn/longhorn-manager/pull/3437

This is similar to the case 10090

**Comment by voarsh2** [comment]
> I will test the longhornio/csi-attacher:v4.6.1 image now.

I still cannot confirm this has helped FYI, just yesterday I needed to remove a VA for a PVC.

**Comment by PhanLe1010** [comment]
> @SNThrailkill From you logs we found two insights
> 
> 1. Many of your daily backups created by the recurring job failed due to missing snapshots. We are still unsure why the snapshots were missing and will continue investigating.
>    
>    * Please also assist in checking if there is any other operation that might be deleting the snapshots at 00:00 when the daily recurring job starts.
> 2. As a result of point 1, the volume was automatically attached by Longhorn for the backup, but it wasn't detached because the backup remained in the "Pending" state due to the missing snapshot. This is why the volume stayed in the attached state.
>    
>    * To resolve this, we will introduce a maximum retry mechanism for the backup process to wait for the snapshot.
> 
> Please help us to open another issue and we can address these two points there as these might not be the same as this issue, thanks.
> 
> cc @derekbit @c3y1huang

Just so we are on the same page @derekbit @ChanYiLin @SNThrailkill

1. The `backup-controller-*` tickets inside `volumeattachments.longhorn.io` CR should NOT be the reason which blocks the volume from attaching to a new node because these are interruptable tickets. See a similar story at https://github.com/longhorn/longhorn/issues/10090#issuecomment-2576346823 . From the context, I assume that you are looking at the volume `ghost-marisela-db` in the support bundle `support-bundle-2025-01-02t20-18-15z`.
2. I am still investigating but I don't know why snapshot is missing for the backup CR. I feel we should continue to investigate this point.

**Comment by SNThrailkill** [comment]
> @SNThrailkill From you logs we found two insights
> 
> 1. Many of your daily backups created by the recurring job failed due to missing snapshots. We are still unsure why the snapshots were missing and will continue investigating.
>    
>    * Please also assist in checking if there is any other operation that might be deleting the snapshots at 00:00 when the daily recurring job starts.
> 2. As a result of point 1, the volume was automatically attached by Longhorn for the backup, but it wasn't detached because the backup remained in the "Pending" state due to the missing snapshot. This is why the volume stayed in the attached state.
>    
>    * To resolve this, we will introduce a maximum retry mechanism for the backup process to wait for the snapshot.
> 
> Please help us to open another issue and we can address these two points there as these might not be the same as this issue, thanks.
> 
> cc @derekbit @c3y1huang

Thank you all for looking into the issue. I will open up another ticket and start addressing comments there
